apiVersion: "v1"
kind: "PersistentVolume"
metadata:
  name: "pv0001-nfs"
spec:
  capacity:
    storage: "10Gi"
  accessModes:
    - "ReadWriteOnce"
  nfs:
    path: "/volume2/NFS"
    server: "192.168.2.11"
  persistentVolumeReclaimPolicy: "Recycle"
